# -*- coding: utf-8 -*-
"""tas_kagit_makas_BUKET_KALFA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jMdSOONgLCXtyGjf1nmYv0J-Do4qinpA
"""

import random

def tas_kagit_makas_BUKET_KALFA():
    print("Taş, Kağıt, Makas Oyunu'na Hoş Geldiniz!")
    print("Kurallar:")
    print("1. Taş, makası kırar.")
    print("2. Makas, kağıdı keser.")
    print("3. Kağıt, taşı sarar.")
    print("4. İki taraf da ilk iki turu kazanana kadar oyun devam eder.")
    print("5. Oyunu kazanmak için ilk iki turu kazanmanız gerekir.")
    print("Oynamak için taş, kağıt veya makas yazın. Oyunu bitirmek için 'çıkış' yazın.")

    # Oyun döngüsü
    while True:
        oyuncu_galibiyetleri = 0
        bilgisayar_galibiyetleri = 0
        tur_sayisi = 0

        while oyuncu_galibiyetleri < 2 and bilgisayar_galibiyetleri < 2:
            # Kullanıcıdan seçim al
            oyuncu_secim = input("\nTaş, Kağıt veya Makas seçin: ").lower()

            # Oyunun sonlandırılması
            if oyuncu_secim == 'çıkış':
                print("Oyunu bitiriyorsunuz. Görüşmek üzere!")
                return

            if oyuncu_secim not in ['taş', 'kağıt', 'makas']:
                print("Geçersiz seçenek! Lütfen tekrar deneyin.")
                continue

            # Bilgisayarın seçim yapması
            bilgisayar_secim = random.choice(['taş', 'kağıt', 'makas'])
            print(f"Bilgisayarın seçimi: {bilgisayar_secim}")

            # Tur sonucunu belirleme
            if oyuncu_secim == bilgisayar_secim:
                print("Bu tur berabere!")
            elif (oyuncu_secim == 'taş' and bilgisayar_secim == 'makas') or \
                 (oyuncu_secim == 'kağıt' and bilgisayar_secim == 'taş') or \
                 (oyuncu_secim == 'makas' and bilgisayar_secim == 'kağıt'):
                print("Bu turu kazandınız!")
                oyuncu_galibiyetleri += 1
            else:
                print("Bu turu bilgisayar kazandı!")
                bilgisayar_galibiyetleri += 1

            # Tur sonucunu ekrana yazdırma
            tur_sayisi += 1
            print(f"Tur Sonuçları: Oyuncu - {oyuncu_galibiyetleri}, Bilgisayar - {bilgisayar_galibiyetleri}")

        # Oyunun galibini belirleme
        if oyuncu_galibiyetleri == 2:
            print("\nTebrikler! Oyunu kazandınız!")
        else:
            print("\nBilgisayar kazandı! Bir sonraki oyunda şansınızı deneyin.")

        # Devam etme isteği
        while True:
            devam_et = input("\nBaşka bir oyun oynamak ister misiniz? (Evet/Hayır): ").lower()
            if devam_et in ['evet', 'hayır']:
                break
            print("Geçersiz giriş! Lütfen 'Evet' veya 'Hayır' yazın.")

        if devam_et == 'hayır':
            print("Oyunu bitiriyorsunuz. Görüşmek üzere!")
            break

# Fonksiyonu çalıştırma
tas_kagit_makas_BUKET_KALFA()